blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/selfish/obsidian-task-planner/discussions
    about: Ask questions or discuss ideas with the community
